---
kind: pipeline
type: kubernetes
name: matrix-1

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cop-cypress:4.11.0-node13 -f Dockerfile --build-arg CYPRESS_VERSION=4.11.0 --build-arg NODE_VERSION=13 .
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push

- name: vulnerability_scan
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cop-cypress:4.11.0-node13
    LOCAL_IMAGE: true
    SERVICE_URL: http://anchore-submission-server:10080
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  commands:
  - docker build --rm=true -f Dockerfile -t cop-cypress:4.11.0-node13 --build-arg CYPRESS_VERSION=4.11.0 --build-arg NODE_VERSION=13 . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date="$(date)" --label org.label-schema.vcs-ref=4.11.0-node13 --label org.label-schema.vcs-url="https://github.com/UKHomeOffice/cop-cypress.git"
  - docker tag cop-cypress:4.11.0-node13 quay.io/ukhomeofficedigital/cop-cypress:4.11.0-node13
  - echo $${DOCKER_PASSWORD} | docker login -u $${DOCKER_USERNAME} --password-stdin quay.io
  - docker push quay.io/ukhomeofficedigital/cop-cypress:4.11.0-node13
  - docker rmi cop-cypress:4.11.0-node13
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  volumes:
  - name: dockersock
    path: /var/run
  when:
    branch:
    - master
    event:
    - push

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - 4.11.0-node13 - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
  - /anchore-submission server
  environment:
    ANCHORE_URL: acp-anchore.acp.homeoffice.gov.uk
    REGISTRY_URL: acp-ephemeral-registry.acp.homeoffice.gov.uk
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

---
kind: pipeline
type: kubernetes
name: matrix-2

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cop-cypress:5.1.0-node13 -f Dockerfile --build-arg CYPRESS_VERSION=5.1.0 --build-arg NODE_VERSION=13 .
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push

- name: vulnerability_scan
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cop-cypress:5.1.0-node13
    LOCAL_IMAGE: true
    SERVICE_URL: http://anchore-submission-server:10080
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  commands:
  - docker build --rm=true -f Dockerfile -t cop-cypress:5.1.0-node13 --build-arg CYPRESS_VERSION=5.1.0 --build-arg NODE_VERSION=13 . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date="$(date)" --label org.label-schema.vcs-ref=5.1.0-node13 --label org.label-schema.vcs-url="https://github.com/UKHomeOffice/cop-cypress.git"
  - docker tag cop-cypress:5.1.0-node13 quay.io/ukhomeofficedigital/cop-cypress:5.1.0-node13
  - echo $${DOCKER_PASSWORD} | docker login -u $${DOCKER_USERNAME} --password-stdin quay.io
  - docker push quay.io/ukhomeofficedigital/cop-cypress:5.1.0-node13
  - docker rmi cop-cypress:5.1.0-node13
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  volumes:
  - name: dockersock
    path: /var/run
  when:
    branch:
    - master
    event:
    - push

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - 5.1.0-node13 - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
  - /anchore-submission server
  environment:
    ANCHORE_URL: acp-anchore.acp.homeoffice.gov.uk
    REGISTRY_URL: acp-ephemeral-registry.acp.homeoffice.gov.uk
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

---
kind: pipeline
type: kubernetes
name: matrix-3

platform:
  os: linux
  arch: amd64

steps:
- name: synch_secrets
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/cop-secrets
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: DEV_DRONE_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: DEV_DRONE_AWS_SECRET_ACCESS_KEY
    DEPLOY_ENV: dev
    DRONE_SERVER: https://drone-gh.acp.homeoffice.gov.uk
    DRONE_TOKEN:
      from_secret: DRONE_V1_PUBLIC_TOKEN
    DRONE_VERSION: ${DRONE_SYSTEM_VERSION}
  when:
    event:
    - promote
    target:
    - secrets

- name: build
  pull: if-not-exists
  image: docker:19.03.12-dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! -e /var/run/docker.sock ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t cop-cypress:5.2.0-node13 -f Dockerfile --build-arg CYPRESS_VERSION=5.2.0 --build-arg NODE_VERSION=13 .
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
    - push

- name: vulnerability_scan
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: cop-cypress:5.2.0-node13
    LOCAL_IMAGE: true
    SERVICE_URL: http://anchore-submission-server:10080
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  commands:
  - docker build --rm=true -f Dockerfile -t cop-cypress:5.2.0-node13 --build-arg CYPRESS_VERSION=5.2.0 --build-arg NODE_VERSION=13 . --pull=true --label org.label-schema.schema-version=1.0 --label org.label-schema.build-date="$(date)" --label org.label-schema.vcs-ref=5.2.0-node13 --label org.label-schema.vcs-url="https://github.com/UKHomeOffice/cop-cypress.git"
  - docker tag cop-cypress:5.2.0-node13 quay.io/ukhomeofficedigital/cop-cypress:5.2.0-node13
  - echo $${DOCKER_PASSWORD} | docker login -u $${DOCKER_USERNAME} --password-stdin quay.io
  - docker push quay.io/ukhomeofficedigital/cop-cypress:5.2.0-node13
  - docker rmi cop-cypress:5.2.0-node13
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_PASSWORD
    DOCKER_USERNAME:
      from_secret: QUAY_USERNAME
  volumes:
  - name: dockersock
    path: /var/run
  when:
    branch:
    - master
    event:
    - push

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - 5.2.0-node13 - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: docker:19.03.12-dind
  volumes:
  - name: dockersock
    path: /var/run

- name: anchore-submission-server
  image: docker.digital.homeoffice.gov.uk/acp-anchore-submission:latest
  commands:
  - /anchore-submission server
  environment:
    ANCHORE_URL: acp-anchore.acp.homeoffice.gov.uk
    REGISTRY_URL: acp-ephemeral-registry.acp.homeoffice.gov.uk
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

...
